### ISSUE TITLE
Фрейм читается со сдвигом

### ISSUE THREAD

**Issue by NikolayLiber** [contactless/wb-mqtt-serial#75]
Попробовал прицепить к контроллеру по RS485 имеющийся у меня китайский термометр-гигрометр. Возникает следующая ситуация: при чтении ответа от датчика перед фреймом возникает лишний нулевой байт из-за чего весь фрейм сдвигается, последний байт фрейма выбрасывается и не совпадает CRC

root@wirenboard-AAKTIXM7:~# wb-mqtt-serial -c /etc/wb-mqtt-serial.conf -d
address: 0
address: 1
Setting up devices at </dev/ttyRS485-1 9600 8 N1 timeout 500>
CreateDevice: temp-humidity-sensor_5 (Temperature and humidity sensor) @ 5 -- protocol: modbus
AddRegister: 0x7f81dae0
AddRegister: 0x7f81ddd0
Adding range: 2 holding(s) @ 0 of device modbus:5
modbus: read 2 holding(s) @ 0 of device modbus:5
Write: 05 03 00 00 00 02Connected with code 0
 c5 8f
ReadFrame: **_00_** 05 03 04 00 F6 00 79 9E
read noise: 23
read noise: 00
ModbusRTU::ReadRegisterRange(): failed to read 2 holding(s) @ 0 of device modbus:5: Serial protocol error: invalid crc

В чем может быть проблема? Этот же самый датчик у меня без проблем читается в NodeRED на компьютере через USB адаптер RS485.

Шаблон:

{
    "device_ttype": "Temperature and humidity sensor",
    "device": {
        "name": "Temperature and numidity sensor",
        "id": "temp-humidity-sensor",
        "max_read_registers": 2,

        "channels": [
            {
                "name": "Temperature",
                "reg_type": "holding",
                "address": 0,
                "type": "value",
                "format": "s16",
                "scale": 0.1
            },
            {
                "name": "Humidity",
                "reg_type": "holding",
                "address": 1,
                "type": "value",
                "format": "s16",
                "scale": 0.1
            }
        ]
    }
}

**Comment by evgeny-boger** [comment]
Спасибо за сообщение, но проблема может быть и во внешнем устройстве, и в железе Wiren Board, и в других компонентах Wiren Board. 
Прошу ограничиться темой на сайте техподдержки: https://forum.wirenboard.com/t/sdvig-frejma-modbus-pri-chtenii-otveta-ot-ustrojstva/2196/2 .
